### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by bashu** [reavis/django-cron#2]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by bashu** [comment]
@reavis sup?

**Comment by reavis** [comment]
It looks like https://github.com/Ixxy-Open-Source/django-cron is a much more actively maintained fork. I would suggest using it instead and checking in with the maintainers there about contributing.

**Comment by bashu** [comment]
@reavis yes, but this project already have its own small community (see stars above) I want to save it. What do you think?
